services:
  api:
    image: ghcr.io/feifxi/twitter-aws-go-api:latest
    container_name: twitter-aws-go-api
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=production
      - AWS_REGION=${AWS_REGION}
    restart: unless-stopped
    
    # ป้องกัน Log กิน Disk EC2 เต็ม
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"